stages:
  - install
  - test
  - deploy

deploy_develop:
  stage: install
  script:
    - node -v
    - yarn -v
    - yarn

deploy_develop:
  stage: test
  script:
    - yarn test

deploy_stage:
  stage: deploy
  script:
    - chmod +x ci/deploy_stage.sh
    - ci/deploy_stage.sh
  only:
    - main
