stages:
  - test
  - deploy

deploy_develop:
  stage: test
  script:
    - yarn test
  only:
    - dev

deploy_stage:
  stage: deploy
  script:
    - chmod +x ci/deploy_stage.sh
    - ci/deploy_stage.sh
  only:
    - main
