stages:
  - test
  - deploy
  - publish

test_stage:
  stage: test
  script:
    - yarn
    - yarn test

deploy_stage:
  stage: deploy
  script:
    - chmod +x ci/deploy_stage.sh
    - ci/deploy_stage.sh
    - chmod +x ci/publish.sh
    - ci/publish.sh
  only:
    - main
