stages:
  - deploy

deploy_develop:
  stage: deploy
  script:
    - ci/deploy_develop.sh
  only:
    - develop

deploy_stage:
  stage: deploy
  script:
    - chmod +x ci/deploy_stage.sh
    - ci/deploy_stage.sh
  only:
    - master
