stages:
  - test
  - deploy
  - publish

test_stage:
  stage: test
  script:
    - yarn
    - yarn test

deploy_stage:
  stage: deploy
  script:
    - chmod +x ci/deploy_stage.sh
    - ci/deploy_stage.sh
    - yarn build
    - echo "$NPM_USER_NAME"
    - npm publish
  only:
    - main
