version: 18
jobs:
- name: CI
  jobExecutor: internal
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build
    runInContainer: true
    image: node:14.19.1
    interpreter: !DefaultInterpreter
      commands:
      - set -e
      - yum install -y jq
      - ''
      - yarn
      - export CI=true
      - yarn test
      - yarn build
      - ''
      - '# parse and store package version into a file which '
      - '# will be used later to tag docker image'
      - jq -r '.version' package.json > version.txt
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
stepTemplates:
- name: test template
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: install
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - yarn
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: test
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - yarn test
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
