version: 18
jobs:
- name: checkout
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PullRepository
    name: pull
    remoteUrl: https://onedev.hxkj.vip/vue3-hash-calendar.git
    syncToChildProject: false
    userName: t@tsy6.com
    passwordSecret: pwd
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: install
    runInContainer: false
    image: 1dev/server
    interpreter: !DefaultInterpreter
      commands:
      - yarn
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
stepTemplates:
- name: test template
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: install
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - yarn
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: test
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - yarn test
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
